[package]
name = "descriptor-encrypt"
version = "0.1.0"
edition = "2024"
authors = ["Joshua Doman <joshsdoman@gmail.com>"]
license = "CC0-1.0"

[features]
default = ["std"]
std = ["bitcoin/std"]
compiler = []
trace = []

[dependencies]
anyhow = "1.0.98"
bitcoin = "0.32.5"
chacha20 = "0.9.1"
chacha20poly1305 = "0.10.1"
miniscript = "12.3.2"
rand = "0.9.1"
sha2 = "0.10.9"
