[package]
name = "threshold-tree"
version = "0.1.0"
description = "A library for iterating over paths through a tree of threshold conditions"
keywords = ["tree", "threshold", "combinatoric", "iterator"]

authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
itertools.workspace = true
miniscript.workspace = true